travis:
  secure:
    BINSTAR_TOKEN: KMhvksJwMlcdDolmf4q5HsAykDI/Ujpc8Mi1R1w4Yk4eI9weB4RulSR3X6f5thuvMgt5ztJk36zw+NgRiPn7ntJgtpOoiZFAbBYc8rcxtlorkfC72gP0NFcGQQNiw96Tb2DIDzNk3JxVpgzscddsyb0YkUUEqQ2c4SyHy9fFu1KftsTuv7nwLRZLnp1801isXYPIQ+iJrKFOO4TFkUcvTfmq8DYb5WEsTTfhjFUjlXwXlw9Ox76SdJ/qoPEmYe9CXry9Nf6NSnZgvq8vY/o+aOSbItknkMFiv70Vn6Vq+fejtUjKbY1JLWGojMUPHWrrH8raDIaQvfOzNk/kh7IiBMfCdD7wC163L5imSibuo8tEengjDxKjJgazxI73267INTgCrr6j8inCy9K4lBs4Hp76sjkdvQCxwcx/46MmOzrXxYeK8EyBRLIiNgbNQur/0R7LNLkwORgFtYtpxcOKp/jwAu2yQb/KdSecigXdrrHst3BUfl1XIoKqnjBXTp353njjeDYZJHz4UwpLapAtEFEefMjdsq+twwAGcMDBneRZOxguuKSYVv3dHhj3E15d6rgpFrhahnDiQlLrZcB4I3wPkU1ZfRomn37N0v/stk0HMsPKM4wSIZpnxA+yQdmZjrAlWcIvennrvs1dPgr/DzhvHBsv5eoKr0Ozl/+3uV0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
